sudo: required

language: java
jdk:
   - oraclejdk7

cache:
   directories:
     - '$HOME/.m2/repository'

before_install: sudo rm /etc/mavenrc
install: /bin/true
script: mvn clean install -V -Prun-its -B -e