safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"
      author: "Red Hat"

siteTitle: "Red Hat"
projectTitle: "PME"
title: "POM Manipulation Extension"
tagline: "Standardize Your Builds"
owner: "Red Hat"
ownerEmail: ncross@redhat.com

markdown: kramdown
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
